version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.x
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            # Upgrade pip and install pytest and any other dependencies from requirements.txt
          
            python -m pip install --upgrade pip
            pip install pytest
            if [ -f requirements.txt ]; then pip install -r ./ci_testing/requirements.txt; fi
      - run:
          name: Run PyTest
          command: |
            pytest ./ci_testing/ci_tests/test.py